steps:
  - name: python
    entrypoint: python
    args: ["-m", "pip", "install", "--upgrade", "pip", "--user"]
  - name: python
    entrypoint: python
    args: ["-m", "pip", "install", "-r", "requirements.txt", "--user"]
    dir: 'pull_linkedin_follower_count'
  - name: python
    entrypoint: python
    args: ["-m", "pytest", "-v", "--cov"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'pull_linkedin_follower_count_cicd', '--region', 'asia-east1', '--trigger-http', '--runtime', 'python311', '--entry-point', 'validate_http']
    dir: 'pull_linkedin_follower_count'
options:
  logging: CLOUD_LOGGING_ONLY
